CREATE TABLE
IF NOT EXISTS pinballer_locations
(
	location_id int4 NOT NULL
	GENERATED BY DEFAULT AS IDENTITY,
	location_address varchar
(255) NOT NULL,
	location_name varchar
(255) NOT NULL,
	CONSTRAINT pinballer_location_pk PRIMARY KEY
(location_id)
);
