CREATE TABLE
IF NOT EXISTS pinballer_users
(
    pinballer_user_id int NOT NULL
    GENERATED BY DEFAULT AS IDENTITY,
	user_first_name varchar
(255) NOT NULL,
	user_last_name varchar
(255) NOT NULL,
	user_nick_name varchar
(255) NOT NULL,
	user_email varchar
(255) NOT NULL,
	user_password varchar
(255) NOT NULL,
	admin_access bool NOT NULL DEFAULT false,
	
	CONSTRAINT pinballer_users_pk PRIMARY KEY
(pinballer_user_id)
);
