
-- Drop table

-- DROP TABLE pinballer_scores;

CREATE TABLE pinballer_scores
(
    score_id int4 NOT NULL
    GENERATED BY DEFAULT AS IDENTITY,
	score_value int4 NOT NULL,
	pinballer_user_id int4 NOT NULL,
	machine_id int4 NOT NULL,
	score_date timestamp NOT NULL DEFAULT now
    ()
);

    ALTER TABLE pinballer_scores ADD CONSTRAINT pinballer_scores_fk FOREIGN KEY (pinballer_user_id) REFERENCES pinballer_users(pinballer_user_id);
    ALTER TABLE pinballer_scores ADD CONSTRAINT pinballer_scores_fk_1 FOREIGN KEY (machine_id) REFERENCES pinballer_machines(machine_id);
